"""Creacion Inicial del Modelo Industrial

Revision ID: d820a37b3e0b
Revises: 
Create Date: 2026-03-12 14:57:23.885475

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd820a37b3e0b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dim_estaciones',
    sa.Column('tenant_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('nombre', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('tipo', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('activa', sa.Boolean(), nullable=False),
    sa.Column('posicion_linea', sa.Integer(), nullable=False),
    sa.Column('ramal', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('parent_id', sqlmodel.sql.sqltypes.GUID(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['dim_estaciones.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dim_estaciones_tenant_id'), 'dim_estaciones', ['tenant_id'], unique=False)
    op.create_table('dim_motivos_parada',
    sa.Column('tenant_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('nombre', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('tipo_parada', sa.Enum('PLANIFICADA', 'NO_PLANIFICADA', name='tipoparada'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dim_motivos_parada_tenant_id'), 'dim_motivos_parada', ['tenant_id'], unique=False)
    op.create_table('dim_operarios',
    sa.Column('tenant_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('legajo', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('nombre_completo', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dim_operarios_legajo'), 'dim_operarios', ['legajo'], unique=False)
    op.create_index(op.f('ix_dim_operarios_tenant_id'), 'dim_operarios', ['tenant_id'], unique=False)
    op.create_table('dim_turnos',
    sa.Column('tenant_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('nombre', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('hora_inicio', sa.Time(), nullable=False),
    sa.Column('hora_fin', sa.Time(), nullable=False),
    sa.Column('descanso_minutos', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dim_turnos_tenant_id'), 'dim_turnos', ['tenant_id'], unique=False)
    op.create_table('maestro_skus',
    sa.Column('tenant_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('codigo_sku', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('descripcion', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('modelo', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('medida', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('tiempo_ciclo_teorico', sa.Float(), nullable=False),
    sa.Column('umbral_calidad', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('codigo_sku')
    )
    op.create_index(op.f('ix_maestro_skus_tenant_id'), 'maestro_skus', ['tenant_id'], unique=False)
    op.create_table('ordenes_produccion',
    sa.Column('tenant_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('id_orden', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('plan_fecha', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('estado', sa.Enum('ABIERTA', 'EN_PROGRESO', 'CERRADA', name='estadoorden'), nullable=False),
    sa.PrimaryKeyConstraint('id_orden')
    )
    op.create_index(op.f('ix_ordenes_produccion_tenant_id'), 'ordenes_produccion', ['tenant_id'], unique=False)
    op.create_table('asignaciones_turno',
    sa.Column('tenant_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('estacion_fk', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('operario_fk', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('turno_fk', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.ForeignKeyConstraint(['estacion_fk'], ['dim_estaciones.id'], ),
    sa.ForeignKeyConstraint(['operario_fk'], ['dim_operarios.id'], ),
    sa.ForeignKeyConstraint(['turno_fk'], ['dim_turnos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_asignaciones_turno_tenant_id'), 'asignaciones_turno', ['tenant_id'], unique=False)
    op.create_table('eventos_escaneo',
    sa.Column('tenant_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('barcode', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('estacion_fk', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('orden_fk', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('operario_fk', sqlmodel.sql.sqltypes.GUID(), nullable=True),
    sa.Column('es_retrabajo', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['estacion_fk'], ['dim_estaciones.id'], ),
    sa.ForeignKeyConstraint(['operario_fk'], ['dim_operarios.id'], ),
    sa.ForeignKeyConstraint(['orden_fk'], ['ordenes_produccion.id_orden'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_eventos_escaneo_tenant_id'), 'eventos_escaneo', ['tenant_id'], unique=False)
    op.create_index('ix_tenant_barcode', 'eventos_escaneo', ['tenant_id', 'barcode'], unique=False)
    op.create_table('items_orden',
    sa.Column('tenant_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('orden_fk', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('sku_fk', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('cantidad_target', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['orden_fk'], ['ordenes_produccion.id_orden'], ),
    sa.ForeignKeyConstraint(['sku_fk'], ['maestro_skus.codigo_sku'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_items_orden_tenant_id'), 'items_orden', ['tenant_id'], unique=False)
    op.create_table('paradas_detectadas',
    sa.Column('tenant_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('estacion_fk', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('inicio', sa.DateTime(), nullable=False),
    sa.Column('fin', sa.DateTime(), nullable=True),
    sa.Column('duracion_segundos', sa.Float(), nullable=True),
    sa.Column('estado', sa.Enum('PENDIENTE', 'CLASIFICADA', name='estadoparada'), nullable=False),
    sa.Column('motivo_fk', sqlmodel.sql.sqltypes.GUID(), nullable=True),
    sa.ForeignKeyConstraint(['estacion_fk'], ['dim_estaciones.id'], ),
    sa.ForeignKeyConstraint(['motivo_fk'], ['dim_motivos_parada.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_paradas_detectadas_tenant_id'), 'paradas_detectadas', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_paradas_detectadas_tenant_id'), table_name='paradas_detectadas')
    op.drop_table('paradas_detectadas')
    op.drop_index(op.f('ix_items_orden_tenant_id'), table_name='items_orden')
    op.drop_table('items_orden')
    op.drop_index('ix_tenant_barcode', table_name='eventos_escaneo')
    op.drop_index(op.f('ix_eventos_escaneo_tenant_id'), table_name='eventos_escaneo')
    op.drop_table('eventos_escaneo')
    op.drop_index(op.f('ix_asignaciones_turno_tenant_id'), table_name='asignaciones_turno')
    op.drop_table('asignaciones_turno')
    op.drop_index(op.f('ix_ordenes_produccion_tenant_id'), table_name='ordenes_produccion')
    op.drop_table('ordenes_produccion')
    op.drop_index(op.f('ix_maestro_skus_tenant_id'), table_name='maestro_skus')
    op.drop_table('maestro_skus')
    op.drop_index(op.f('ix_dim_turnos_tenant_id'), table_name='dim_turnos')
    op.drop_table('dim_turnos')
    op.drop_index(op.f('ix_dim_operarios_tenant_id'), table_name='dim_operarios')
    op.drop_index(op.f('ix_dim_operarios_legajo'), table_name='dim_operarios')
    op.drop_table('dim_operarios')
    op.drop_index(op.f('ix_dim_motivos_parada_tenant_id'), table_name='dim_motivos_parada')
    op.drop_table('dim_motivos_parada')
    op.drop_index(op.f('ix_dim_estaciones_tenant_id'), table_name='dim_estaciones')
    op.drop_table('dim_estaciones')
    # ### end Alembic commands ###
